# Test 2025-05-18 at 06:14:04

name: Test
run-name: pythonParallelProcesses

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Run in parallel
      run: |
        python3 oneByOne.py
